# Generated by Django 4.1.4 on 2022-12-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(verbose_name='date published')),
                ('describe', models.TextField(max_length=4000)),
                ('time_prepair', models.PositiveIntegerField()),
                ('difficulty', models.CharField(blank=True, choices=[('N', 'NOOB'), ('E', 'Łatwy'), ('M', 'Średni'), ('H', 'Trudny'), ('S', 'MasterChef')], max_length=1)),
            ],
        ),
    ]
