# Generated by Django 4.1.4 on 2022-12-28 17:26

from django.db import migrations, models
import strona.pathandrename


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0004_alter_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='linkYT',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to=strona.pathandrename.PathAndRename.wrapper),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author_photo', models.ImageField(upload_to=strona.pathandrename.PathAndRename.wrapper)),
                ('surname', models.CharField(max_length=50)),
                ('social_IG', models.URLField(max_length=500)),
                ('social_SNAP', models.URLField(max_length=500)),
                ('social_FB', models.URLField(max_length=500)),
                ('social_PH', models.URLField(max_length=500)),
                ('social_OF', models.URLField(max_length=500)),
                ('recipes', models.ManyToManyField(blank=True, related_name='author', to='strona.recipe')),
            ],
        ),
    ]
