# Generated by Django 4.1.4 on 2022-12-28 17:46

from django.db import migrations, models
import strona.pathandrename


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_rename_name_author_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(upload_to=strona.pathandrename.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_FB',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_IG',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_OF',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_PH',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_SNAP',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to=strona.pathandrename.PathAndRename.wrapper),
        ),
    ]
