# Generated by Django 4.1.4 on 2022-12-28 17:54

from django.db import migrations, models
import strona.pathandrename


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_alter_author_author_photo_alter_author_social_fb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(upload_to=strona.pathandrename.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to=strona.pathandrename.PathAndRename.wrapper),
        ),
    ]
